-- ====================================================================
-- SMILECARE DENTAL CLINIC - DATABASE SCHEMA & SUPABASE SETUP
-- ====================================================================
-- File: database/schema.sql
-- Description: Complete SQL commands to recreate the Supabase database,
-- tables, relations, storage buckets, and RLS security policies.
-- ====================================================================

-- --------------------------------------------------------------------
-- 1. DOCTORS TABLE
-- Stores doctor profiles, specializations, email & auth linkages.
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.doctors (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    specialization TEXT,
    email TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Comments on doctors table columns
COMMENT ON TABLE public.doctors IS 'Stores registered clinic doctors and specializations';
COMMENT ON COLUMN public.doctors.id IS 'Unique identifier for the doctor';
COMMENT ON COLUMN public.doctors.name IS 'Full name of the doctor (e.g., Dr. Rajesh Kumar)';
COMMENT ON COLUMN public.doctors.specialization IS 'Area of dental expertise (e.g., Orthodontist, Endodontist)';
COMMENT ON COLUMN public.doctors.email IS 'Doctor email address used for portal login authentication';


-- --------------------------------------------------------------------
-- 2. APPOINTMENTS TABLE
-- Stores patient booking details, assigned doctor, status & document URL.
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_name TEXT NOT NULL,
    age INT NOT NULL,
    gender TEXT,
    email TEXT,
    mobile TEXT NOT NULL,
    issue TEXT NOT NULL,
    document_url TEXT,
    appointment_date DATE NOT NULL,
    appointment_time TEXT NOT NULL,
    doctor_id UUID REFERENCES public.doctors(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'Pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Comments on appointments table columns
COMMENT ON TABLE public.appointments IS 'Stores all patient appointment bookings and live statuses';
COMMENT ON COLUMN public.appointments.patient_name IS 'Full name of the patient';
COMMENT ON COLUMN public.appointments.age IS 'Age of the patient in years';
COMMENT ON COLUMN public.appointments.gender IS 'Gender of the patient (Male/Female/Other)';
COMMENT ON COLUMN public.appointments.email IS 'Patient optional contact email';
COMMENT ON COLUMN public.appointments.mobile IS '10-digit mobile number used for lookup and identification';
COMMENT ON COLUMN public.appointments.issue IS 'Dental problem / concern description';
COMMENT ON COLUMN public.appointments.document_url IS 'Public Supabase storage URL for attached prescription/X-ray file';
COMMENT ON COLUMN public.appointments.appointment_date IS 'Selected appointment date';
COMMENT ON COLUMN public.appointments.appointment_time IS 'Selected appointment time slot (e.g., 10:00 AM)';
COMMENT ON COLUMN public.appointments.doctor_id IS 'Foreign key referencing the assigned doctor';
COMMENT ON COLUMN public.appointments.status IS 'Current appointment status: Pending, Confirmed, Completed, Cancelled';


-- --------------------------------------------------------------------
-- 3. INDEXES FOR HIGH-PERFORMANCE QUERYING
-- Accelerates searches by mobile number, appointment date, and doctor ID.
-- --------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_appointments_mobile ON public.appointments(mobile);
CREATE INDEX IF NOT EXISTS idx_appointments_date ON public.appointments(appointment_date);
CREATE INDEX IF NOT EXISTS idx_appointments_doctor ON public.appointments(doctor_id);
CREATE INDEX IF NOT EXISTS idx_doctors_email ON public.doctors(email);


-- --------------------------------------------------------------------
-- 4. ROW-LEVEL SECURITY (RLS) POLICIES
-- Enables anonymous public booking/lookup and doctor updates.
-- --------------------------------------------------------------------

-- Enable RLS on both tables
ALTER TABLE public.doctors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;

-- Allow public read access to doctors list (for booking form dropdown)
CREATE POLICY "Allow public read access to doctors"
ON public.doctors FOR SELECT TO public
USING (true);

-- Allow public users to insert new appointments (booking form submission)
CREATE POLICY "Allow public insert into appointments"
ON public.appointments FOR INSERT TO public
WITH CHECK (true);

-- Allow public users to read appointments (for patient appointment lookup)
CREATE POLICY "Allow public read access to appointments"
ON public.appointments FOR SELECT TO public
USING (true);

-- Allow public / authenticated users to update appointment status (for cancellation & doctor status updates)
CREATE POLICY "Allow public update access to appointments"
ON public.appointments FOR UPDATE TO public
USING (true)
WITH CHECK (true);


-- --------------------------------------------------------------------
-- 5. STORAGE BUCKET FOR PATIENT DOCUMENTS
-- Creates public storage bucket for uploading prescriptions & X-rays.
-- --------------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public)
VALUES ('patient-documents', 'patient-documents', true)
ON CONFLICT (id) DO NOTHING;

-- Storage RLS Policy: Allow public file uploads
CREATE POLICY "Allow public document uploads"
ON storage.objects FOR INSERT TO public
WITH CHECK (bucket_id = 'patient-documents');

-- Storage RLS Policy: Allow public file views
CREATE POLICY "Allow public document viewing"
ON storage.objects FOR SELECT TO public
USING (bucket_id = 'patient-documents');


-- --------------------------------------------------------------------
-- 6. INITIAL SAMPLE DATA (OPTIONAL REFERENCE DOCTORS)
-- Uncomment and run to insert default doctors if needed.
-- --------------------------------------------------------------------
-- INSERT INTO public.doctors (name, specialization, email) VALUES
-- ('Dr. Rajesh Sharma', 'General Dentistry', 'rajesh@smilecare.com'),
-- ('Dr. Ananya Verma', 'Orthodontics & Braces', 'ananya@smilecare.com'),
-- ('Dr. Vikram Patel', 'Root Canal & Endodontics', 'vikram@smilecare.com')
-- ON CONFLICT (email) DO NOTHING;


-- --------------------------------------------------------------------
-- 7. SUPABASE REALTIME PUBLICATION SETUP
-- Enables real-time web UI updates when email, doctor details, or appointments change.
-- Run this in Supabase SQL Editor if Realtime is not enabled by default.
-- --------------------------------------------------------------------
ALTER PUBLICATION supabase_realtime ADD TABLE public.doctors;
ALTER PUBLICATION supabase_realtime ADD TABLE public.appointments;

