-- ====================================================================
-- SMILECARE DENTAL CLINIC - DATABASE SCHEMA & SUPABASE SETUP
-- ====================================================================
-- File: database/schema.sql
-- Description: Complete SQL commands to recreate the Supabase database,
-- tables, relations, storage buckets, and RLS security policies.
-- ====================================================================

-- --------------------------------------------------------------------
-- 1. DOCTORS TABLE
-- Stores doctor profiles, specializations, email & auth linkages.
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.doctors (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    specialization TEXT,
    email TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Comments on doctors table columns
COMMENT ON TABLE public.doctors IS 'Stores registered clinic doctors and specializations';
COMMENT ON COLUMN public.doctors.id IS 'Unique identifier for the doctor';
COMMENT ON COLUMN public.doctors.name IS 'Full name of the doctor (e.g., Dr. Rajesh Kumar)';
COMMENT ON COLUMN public.doctors.specialization IS 'Area of dental expertise (e.g., Orthodontist, Endodontist)';
COMMENT ON COLUMN public.doctors.email IS 'Doctor email address used for portal login authentication';


-- --------------------------------------------------------------------
-- 2. APPOINTMENTS TABLE
-- Stores patient booking details, assigned doctor, status & document URL.
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_name TEXT NOT NULL,
    age INT NOT NULL,
    gender TEXT,
    email TEXT,
    mobile TEXT NOT NULL,
    issue TEXT NOT NULL,
    document_url TEXT,
    doctor_report_url TEXT,
    diagnosis TEXT,
    medicine TEXT,
    next_visit_date DATE,
    appointment_date DATE NOT NULL,
    appointment_time TEXT NOT NULL,
    doctor_id UUID REFERENCES public.doctors(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'Pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- SQL Migration Command for existing database (Run in Supabase SQL Editor):
-- ALTER TABLE public.appointments 
-- ADD COLUMN IF NOT EXISTS diagnosis TEXT,
-- ADD COLUMN IF NOT EXISTS medicine TEXT,
-- ADD COLUMN IF NOT EXISTS next_visit_date DATE;

-- Comments on appointments table columns
COMMENT ON TABLE public.appointments IS 'Stores all patient appointment bookings and live statuses';
COMMENT ON COLUMN public.appointments.patient_name IS 'Full name of the patient';
COMMENT ON COLUMN public.appointments.age IS 'Age of the patient in years';
COMMENT ON COLUMN public.appointments.gender IS 'Gender of the patient (Male/Female/Other)';
COMMENT ON COLUMN public.appointments.email IS 'Patient optional contact email';
COMMENT ON COLUMN public.appointments.mobile IS '10-digit mobile number used for lookup and identification';
COMMENT ON COLUMN public.appointments.issue IS 'Dental problem / concern description';
COMMENT ON COLUMN public.appointments.document_url IS 'Public Supabase storage URL for patient attached file';
COMMENT ON COLUMN public.appointments.doctor_report_url IS 'Public Supabase storage URL for doctor uploaded prescription/report file';
COMMENT ON COLUMN public.appointments.diagnosis IS 'Doctor checkup diagnosis notes';
COMMENT ON COLUMN public.appointments.medicine IS 'Prescription / medicine instructions';
COMMENT ON COLUMN public.appointments.next_visit_date IS 'Recommended next follow-up appointment date';
COMMENT ON COLUMN public.appointments.appointment_date IS 'Selected appointment date';
COMMENT ON COLUMN public.appointments.appointment_time IS 'Selected appointment time slot (e.g., 10:00 AM)';
COMMENT ON COLUMN public.appointments.doctor_id IS 'Foreign key referencing the assigned doctor';
COMMENT ON COLUMN public.appointments.status IS 'Current appointment status: Pending, Confirmed, Completed, Cancelled';


-- --------------------------------------------------------------------
-- 3. INDEXES FOR HIGH-PERFORMANCE QUERYING
-- Accelerates searches by mobile number, appointment date, and doctor ID.
-- --------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_appointments_mobile ON public.appointments(mobile);
CREATE INDEX IF NOT EXISTS idx_appointments_date ON public.appointments(appointment_date);
CREATE INDEX IF NOT EXISTS idx_appointments_doctor ON public.appointments(doctor_id);
CREATE INDEX IF NOT EXISTS idx_doctors_email ON public.doctors(email);


-- --------------------------------------------------------------------
-- 4. ROW-LEVEL SECURITY (RLS) POLICIES
-- Enables anonymous public booking/lookup and doctor updates.
-- --------------------------------------------------------------------

-- Enable RLS on both tables
ALTER TABLE public.doctors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;

-- Allow public read access to doctors list (for booking form dropdown)
CREATE POLICY "Allow public read access to doctors"
ON public.doctors FOR SELECT TO public
USING (true);

-- Allow public users to insert new appointments (booking form submission)
CREATE POLICY "Allow public insert into appointments"
ON public.appointments FOR INSERT TO public
WITH CHECK (true);

-- Allow public users to read appointments (for patient appointment lookup)
CREATE POLICY "Allow public read access to appointments"
ON public.appointments FOR SELECT TO public
USING (true);

-- Allow public / authenticated users to update appointment status (for cancellation & doctor status updates)
CREATE POLICY "Allow public update access to appointments"
ON public.appointments FOR UPDATE TO public
USING (true)
WITH CHECK (true);


-- --------------------------------------------------------------------
-- 5. STORAGE BUCKET FOR PATIENT DOCUMENTS
-- Creates public storage bucket for uploading prescriptions & X-rays.
-- --------------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public)
VALUES ('patient-documents', 'patient-documents', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Storage RLS Policies: Allow public file uploads, updates and views
DROP POLICY IF EXISTS "Allow public document uploads" ON storage.objects;
DROP POLICY IF EXISTS "Allow public document viewing" ON storage.objects;
DROP POLICY IF EXISTS "Allow public storage uploads" ON storage.objects;
DROP POLICY IF EXISTS "Allow public storage select" ON storage.objects;
DROP POLICY IF EXISTS "Allow public storage update" ON storage.objects;

CREATE POLICY "Allow public storage uploads"
ON storage.objects FOR INSERT TO public
WITH CHECK (bucket_id = 'patient-documents');

CREATE POLICY "Allow public storage update"
ON storage.objects FOR UPDATE TO public
USING (bucket_id = 'patient-documents')
WITH CHECK (bucket_id = 'patient-documents');

CREATE POLICY "Allow public storage select"
ON storage.objects FOR SELECT TO public
USING (bucket_id = 'patient-documents');


-- --------------------------------------------------------------------
-- 6. INITIAL SAMPLE DATA (OPTIONAL REFERENCE DOCTORS)
-- Uncomment and run to insert default doctors if needed.
-- --------------------------------------------------------------------
-- INSERT INTO public.doctors (name, specialization, email) VALUES
-- ('Dr. Rajesh Sharma', 'General Dentistry', 'rajesh@smilecare.com'),
-- ('Dr. Ananya Verma', 'Orthodontics & Braces', 'ananya@smilecare.com'),
-- ('Dr. Vikram Patel', 'Root Canal & Endodontics', 'vikram@smilecare.com')
-- ON CONFLICT (email) DO NOTHING;


-- --------------------------------------------------------------------
-- 7. SUPABASE REALTIME PUBLICATION SETUP
-- Enables real-time web UI updates when email, doctor details, or appointments change.
-- Run this in Supabase SQL Editor if Realtime is not enabled by default.
-- --------------------------------------------------------------------
ALTER PUBLICATION supabase_realtime ADD TABLE public.doctors;
ALTER PUBLICATION supabase_realtime ADD TABLE public.appointments;


-- --------------------------------------------------------------------
-- 8. DOCTOR AVAILABILITY & LEAVES TABLES
-- --------------------------------------------------------------------

-- Table 1: doctor_availability (Weekly schedule per doctor)
CREATE TABLE IF NOT EXISTS public.doctor_availability (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    doctor_id UUID NOT NULL REFERENCES public.doctors(id) ON DELETE CASCADE,
    day_of_week TEXT NOT NULL,
    start_time TIME NOT NULL DEFAULT '10:00:00',
    end_time TIME NOT NULL DEFAULT '18:00:00',
    is_available BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (doctor_id, day_of_week)
);

COMMENT ON TABLE public.doctor_availability IS 'Stores weekly working schedule for doctors';

-- Table 2: doctor_leaves (Specific leave dates marked by doctors)
CREATE TABLE IF NOT EXISTS public.doctor_leaves (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    doctor_id UUID NOT NULL REFERENCES public.doctors(id) ON DELETE CASCADE,
    leave_date DATE NOT NULL,
    reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (doctor_id, leave_date)
);

COMMENT ON TABLE public.doctor_leaves IS 'Stores specific leave dates marked by doctors';

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_doctor_availability_doc ON public.doctor_availability(doctor_id);
CREATE INDEX IF NOT EXISTS idx_doctor_leaves_doc_date ON public.doctor_leaves(doctor_id, leave_date);

-- Enable RLS
ALTER TABLE public.doctor_availability ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.doctor_leaves ENABLE ROW LEVEL SECURITY;

-- RLS Policies: Allow public read, insert, update, delete
CREATE POLICY "Allow public read access to doctor_availability"
ON public.doctor_availability FOR SELECT TO public USING (true);

CREATE POLICY "Allow public insert/update/delete to doctor_availability"
ON public.doctor_availability FOR ALL TO public USING (true) WITH CHECK (true);

CREATE POLICY "Allow public read access to doctor_leaves"
ON public.doctor_leaves FOR SELECT TO public USING (true);

CREATE POLICY "Allow public insert/update/delete to doctor_leaves"
ON public.doctor_leaves FOR ALL TO public USING (true) WITH CHECK (true);

-- Enable Realtime for availability and leaves
ALTER PUBLICATION supabase_realtime ADD TABLE public.doctor_availability;
ALTER PUBLICATION supabase_realtime ADD TABLE public.doctor_leaves;


-- --------------------------------------------------------------------
-- 9. INITIAL SAMPLE AVAILABILITY DATA (Mon-Sat 10 AM - 6 PM, Sunday Off)
-- Populate default availability for all registered doctors
-- --------------------------------------------------------------------
DO $$
DECLARE
    doc RECORD;
    d_day TEXT;
    days_arr TEXT[] := ARRAY['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
BEGIN
    FOR doc IN SELECT id FROM public.doctors LOOP
        FOREACH d_day IN ARRAY days_arr LOOP
            INSERT INTO public.doctor_availability (doctor_id, day_of_week, start_time, end_time, is_available)
            VALUES (
                doc.id, 
                d_day, 
                '10:00:00'::time, 
                '18:00:00'::time, 
                CASE WHEN d_day = 'Sunday' THEN false ELSE true END
            )
            ON CONFLICT (doctor_id, day_of_week) DO NOTHING;
        END LOOP;
    END LOOP;
END $$;


